### ISSUE TITLE
CS-Model keeps all the original metabolites

### ISSUE THREAD

**Issue by migp11** [resendislab/corda#10]
Hi,

I'm using CORDA to generate context-specific model based Recon2.2.

Recon2 dimesions: metabs=5324 rxns=7785
my_CSM: metabs=5324 rxns=4396

Thus my_CSM contains all the metabolites present in the original model.
In fact, if I execute the following line:

`len([m for m in my_CSM.metabolites if len(m.reactions) == 0])`

I get 2311 metabolites, which are not involved in any reaction, and thus, shoul not be part of the model

Hope it helps.
Best
Miguel

**Comment by cdiener** [comment]
Can confirm. Was an oversight from a recent change. Will push a fix.

**Comment by cdiener** [comment]
Ok, should be fixed in 0.4.1.
