### ISSUE TITLE
corda.build() doesn't end 

### ISSUE THREAD

**Issue by ACabbia** [resendislab/corda#12]
Hi! First of all thanks a lot for this implementation!

I am using CORDA to generate several context-specific models from microarray data, one model for each of the 36 individuals in my GEO dataset. I am using Recon2.2 as template. 

The problem is when I call CORDA.build(), it just goes on computing without ending. 
No error messages whatsoever, I even left it run over the weekend but nothing happened.
What is worse is that the problem is not happening in a consistent way, as it presents itself only for some of the 36 individuals in the dataset  (no apparent diffences in the data among individuals) 

I tried to hunt down the problem myself, I think the program hangs when the *.associated() method is called, at line 276 of corda.py. 

Sorry for the poor description of the issue, I couldn't find a way to reproduce it here. 
I hope you can at least point me in the right direction to solve this issue
If you want I can share some code and the reaction confidence 

Best Regards

Andrea

**Comment by cdiener** [comment]
Thanks for the report :)

Could be several things. I think the most obvious candidate is redundancy detection. Could you try running you construction with setting the `n` parameter in `corda.CORDA`? For instance:

```python
from corda import CORDA

opt = CORDA(model, conf, n=10)
```

This limits the search for alternative pathways with the same score to 10 alternatives and might make it terminate earlier.

**Comment by ACabbia** [comment]
Setting `n=10` did not help, the functions still wasn't terminating. I tried again with much smaller values such as `n = 2` and it works.  

Thanks for your help!

Do you have any hypothesis regarding why this issue was occurring only for certain subjects and not for others?

**Comment by cdiener** [comment]
Look like a numerical issue. I will investigate a bit further and get back to you. Thanks!

**Comment by cdiener** [comment]
Hmm, there is nothing super clear. Do you think you could share you confidences for one of the problematic models? If the data is confidential you can send it to `mail (at) cdiener.com`. A csv or pickle of the dictionary would be great.

**Comment by ACabbia** [comment]
no problem. I also attached a script to replicate the issue.

[corda_no_end.zip](https://github.com/resendislab/corda/files/1811910/corda_no_end.zip)

**Comment by cdiener** [comment]
So, I had some problems reproducing your issue. Mostly because I could not find the exact version of the Recon 2.2 model you were using. I tried with the original model from [the publication](https://www.ncbi.nlm.nih.gov/pubmed/27358602) and the [latest version (2.2.05)](https://github.com/u003f/recon2/tree/master/models) but none of the two include exactly the reactions from your confidence list. I ran CORDA with both assigning a confidence of 0 to the reactions that were missing from your list and all reconstructions take <15min for me and give reasonable results (~3500 reactions and they do grow). 

I fixed some small errors in the code but I don't think those were related to your problem. Maybe you could try with the latest Recon 2.2 model (2.2.05) and see whether your issue persists with the last version of the corda package (just uploaded 0.4.2). Also updating cobrapy, optlang and swiglpk might help...

**Comment by ACabbia** [comment]
oh, sorry for that! I downloaded the model from the BioModels Database: 
https://www.ebi.ac.uk/biomodels-main/MODEL1603150001
I noticed that the  Recon2.2 publication has the same link to this BiomodelsDB page, but the version attached in the supplementary material of the paper is different. Which one did you try?  
I'll try to update everything, use the Recon 2.2.05 and see if the issue is still appearing. 

BTW, I am using a score of 3 for the high confidence reactions  and -1 for everything else. Do you think could be related to the problem? should I use 0 or you think it doesn't matter?

Anyway, Thanks a lot for your support!

**Comment by cdiener** [comment]
The first one I tried I also downloaded from Biomodels. I think just working with categories 3 and -1 is fine if you want the smallest model possible. This also only requires running one of the 3 phases of the algorithm so it tends to be faster as well.

**Comment by ACabbia** [comment]
I am closing the issue since can't be replicated.
Thanks again for the support

**Comment by debolina27** [comment]
Hello!

I was facing the same problem and after a series of print statements found out that the solver stalls for some erratic target reactions. Setting a limit on the maximum allowed solve time helps skip those - 

self.model.solver.configuration.timeout = max_time_limit 
(where max_time_limit is the time you want the solver to run for, and adding this line in the associated function before sol = self.model.solver.optimize())
