### ISSUE TITLE
CORDA2?

### ISSUE THREAD

**Issue by juefish** [resendislab/corda#6]
Love the python version of CORDA but any chance you're planning on updating it to CORDA2? Specifically include the mfACHR components as well as the CORDA2 updates. Cheers.

**Comment by cdiener** [comment]
I already included the changes from CORDA 2 in May :smile: Actually made everything a bit faster. Regarding the mfACHR I see that as something apart from the actual CORDA. However, we recently added sampling to cobrapy itself and from the benchmarks I have seen in the paper for mfACHR the cobrapy samplers should be at least as fast. See https://cobrapy.readthedocs.io/en/latest/sampling.html for more info.

**Comment by cdiener** [comment]
Made it clearer now in the Readme. Closing for now, feel free to reopen if you want to add something :)
